<?php

/**
 * Site Errors controller
 *
 * Used for App Errors generated by non supplied or bad database IDS
 *
 * Site Errors controller can be only accessed from within the application itself,
 * So, any request that has errors as controller will be considered as invalid
 *
 * @see App::isControllerValid()
 *

 * @author     Mark Solly <mark.solly@fsg.com.au>
 */

class SiteErrorsController extends Controller{

    /**
     * Initialization method.
     *
     */
    public function initialize(){
    }

    public function noPickupFound()
    {
        //render the error page
        $this->view->renderWithLayouts(Config::get('VIEWS_PATH') . "layout/default/", Config::get('ERRORS_PATH') . 'noPickupFound.php', [
            'pht'   => ": No Pickup Found"
        ]);
    }

    public function noPickupId()
    {
        //render the error page
        Config::setJsConfig('curPage', "errors");
        $this->view->renderWithLayouts(Config::get('VIEWS_PATH') . "layout/default/", Config::get('ERRORS_PATH') . 'noPickupId.php', []);
    }
}
