<input type="hidden" id="eparcel_id" value="<?php echo $this->controller->courier->eParcelId;?>" />
<input type="hidden" id="eparcelexpress_id" value="<?php echo $this->controller->courier->eParcelExpressId;?>" />
<input type="hidden" id="hunters_id" value="<?php echo $this->controller->courier->huntersId;?>" />
<input type="hidden" id="huntersplu_id" value="<?php echo $this->controller->courier->huntersPluId;?>" />
<input type="hidden" id="three3pltruck_id" value="<?php echo $this->controller->courier->threePlTruckId;?>" />
<input type="hidden" id="viclocal_id" value="<?php echo $this->controller->courier->vicLocalId;?>" />
<input type="hidden" id="direct_freight_id" value="<?php echo $this->controller->courier->directFreightId;?>" />
<input type="hidden" id="local_id" value="<?php echo $this->controller->courier->localId;?>" />
<input type="hidden" id="comet_local_id" value="<?php echo $this->controller->courier->cometLocalId;?>" />